language: php
cache:
  directories:
  - node_modules
install:
- npm install
script:
- node_modules/.bin/gulp build
before_deploy:
- node_modules/.bin/gulp release
deploy:
  provider: releases
  api_key:
    secure: MqJcW6ngec4MqW2McNieNme+w5IVV18OsRRFPUTpz1cJ3pQ3gzxuKCvUFSBoVzvTNIikeduMeMpLH7o8Zeyf+yNdQxpHF6frgrhkJ+DNmwC/VJ8Iq2HjGD32bZhVHKAMU2ZT3XCHjopc8BMIKaS98IwvXD5I25RS3FKEEziPQ4O4yY1EgAa4ChZYkotA8Xsn0vusCExChzO5ETE+xAgYFWlb5tQdOR3rHINNh6RGjWLLRh/nshZ1GW6SfMQ2kj49RYIzA9bV9Hbwt4rKi+YAgy0otWMCHcb8Wvu3kda2WBb/B5eARuhjp1UT8jJkS1gBX5zPOhY2FI93nJx9yYEpq/BG+MWi7dyoXLIFrdhow6SCCx7Tpy0OYGLonM9R5NMeVZ3W/XXYOX9ix6sC7yymHPWV40+LWlpiYZ0p6M6yfZ02zhgIm/sGctCKEmYGlGWc+odko4XvYL+5/wu4C3ZiUNM/Dk/A1oLUQJrtmlFUaBFfyU3w+oqrqB2veMvGoIyB/znMXEnru654zxNQHAi4SyflPEvYvYjE6nSqpKti+l63v5qpiWatTG1gJERWIQ4G7e4k0CO8CE0wC8vLraIiC90PqplX8zkdGSDKch/ktgNl7GTiUhzy/SXN2bC4MB7k3wORjUxFzp6ChEgi9yiQLnjnZnb6tsuyUU2H+QGrYJk=
  file: mc_theme.zip
  on:
    repo: ad-m/mc-theme
    tags: true